import { Researcher } from '@/store/user-store';

export const initialResearchers: Omit<Researcher, 'id' | 'dateAdded'>[] = [
  {
    name: "Dr. Alex Johnson",
    university: "Stanford University",
    field: "Computer Science",
    keywords: ["neural networks", "NLP", "machine learning", "AI", "deep learning", "natural language processing"],
    bio: "Neural networks for natural language processing in academic contexts. Focuses on transformer architectures and attention mechanisms.",
    matchableText: "neural networks NLP machine learning AI deep learning natural language processing transformer attention mechanisms computer science artificial intelligence",
    publications: 23,
    profileURL: "/profile/alex-johnson",
    email: "alex.johnson@stanford.edu",
    verified: true,
    github: "https://github.com/alexjohnsonai",
    linkedin: "https://linkedin.com/in/alexjohnsoncs",
    department: "Computer Science"
  },
  {
    name: "Dr. Maya Patel",
    university: "MIT",
    field: "Artificial Intelligence",
    keywords: ["machine learning", "semantic analysis", "research automation", "data mining", "knowledge graphs"],
    bio: "Machine learning approaches to semantic analysis of research papers. Developing automated systems for scientific literature review.",
    matchableText: "machine learning semantic analysis research automation data mining knowledge graphs artificial intelligence scientific literature review computational linguistics",
    publications: 18,
    profileURL: "/profile/maya-patel",
    email: "mpatel@mit.edu",
    verified: true,
    github: "https://github.com/mayapatel-ai",
    linkedin: "https://linkedin.com/in/mayapatelai",
    department: "Artificial Intelligence Lab"
  },
  {
    name: "Prof. Sam Williams",
    university: "UC Berkeley",
    field: "Data Science",
    keywords: ["knowledge extraction", "data mining", "scientific computing", "big data", "information retrieval"],
    bio: "Automated knowledge extraction from scientific literature using advanced data mining techniques and large-scale computing.",
    matchableText: "knowledge extraction data mining scientific computing big data information retrieval automated systems large scale computing text mining",
    publications: 31,
    profileURL: "/profile/sam-williams",
    email: "swilliams@berkeley.edu",
    verified: true,
    github: "https://github.com/samwilliamsdata",
    linkedin: "https://linkedin.com/in/samwilliamsphd",
    department: "Data Science"
  },
  {
    name: "Dr. Elena Rodriguez",
    university: "Harvard University",
    field: "Biomedical Engineering",
    keywords: ["drug discovery", "deep learning", "biomedical AI", "computational biology", "bioinformatics", "molecular modeling"],
    bio: "AI-driven drug discovery using deep learning models. Specializes in molecular property prediction and drug-target interactions.",
    matchableText: "drug discovery deep learning biomedical AI computational biology bioinformatics molecular modeling molecular property prediction drug target interactions",
    publications: 27,
    profileURL: "/profile/elena-rodriguez",
    email: "erodriguez@harvard.edu",
    verified: false,
    github: "https://github.com/elenarodriguez-bio",
    linkedin: "https://linkedin.com/in/elenarodriguezbio",
    department: "Biomedical Engineering"
  },
  {
    name: "Dr. James Chen",
    university: "Caltech",
    field: "Physics",
    keywords: ["quantum computing", "cryptography", "quantum algorithms", "quantum mechanics", "quantum information"],
    bio: "Quantum computing applications in cryptography. Research focuses on quantum algorithms for secure communication protocols.",
    matchableText: "quantum computing cryptography quantum algorithms quantum mechanics quantum information secure communication protocols quantum cryptography",
    publications: 15,
    profileURL: "/profile/james-chen",
    email: "jchen@caltech.edu",
    verified: true,
    github: "https://github.com/jameschen-quantum",
    department: "Physics"
  },
  {
    name: "Dr. Sarah Thompson",
    university: "Oxford University",
    field: "Cognitive Science",
    keywords: ["cognitive science", "neural networks", "brain modeling", "psychology", "neuroscience", "cognitive psychology"],
    bio: "Cognitive modeling using artificial neural networks. Investigating how brain mechanisms can inform AI architectures.",
    matchableText: "cognitive science neural networks brain modeling psychology neuroscience cognitive psychology artificial neural networks brain mechanisms AI architectures",
    publications: 20,
    profileURL: "/profile/sarah-thompson",
    email: "sthompson@oxford.ac.uk",
    verified: true,
    linkedin: "https://linkedin.com/in/sarahthompsoncog",
    department: "Cognitive Science"
  },
  {
    name: "Dr. Michael Zhang",
    university: "Carnegie Mellon University",
    field: "Robotics",
    keywords: ["robotics", "computer vision", "autonomous systems", "machine learning", "sensor fusion", "SLAM"],
    bio: "Autonomous robotics systems with advanced computer vision capabilities. Focus on SLAM and multi-sensor navigation.",
    matchableText: "robotics computer vision autonomous systems machine learning sensor fusion SLAM navigation multi-sensor robotic perception",
    publications: 22,
    profileURL: "/profile/michael-zhang",
    email: "mzhang@cmu.edu",
    verified: true,
    github: "https://github.com/michaelzhang-robotics",
    linkedin: "https://linkedin.com/in/michaelzhangcmu",
    department: "Robotics Institute"
  },
  {
    name: "Dr. Lisa Park",
    university: "University of Washington",
    field: "Human-Computer Interaction",
    keywords: ["HCI", "user experience", "accessibility", "human factors", "interface design", "usability"],
    bio: "Human-computer interaction research with focus on accessibility and inclusive design for educational technology.",
    matchableText: "HCI human computer interaction user experience accessibility human factors interface design usability inclusive design educational technology",
    publications: 16,
    profileURL: "/profile/lisa-park",
    email: "lpark@uw.edu",
    verified: true,
    github: "https://github.com/lisapark-hci",
    linkedin: "https://linkedin.com/in/lisaparkhci",
    department: "Human-Computer Interaction"
  },
  {
    name: "Dr. David Kumar",
    university: "Georgia Tech",
    field: "Machine Learning",
    keywords: ["reinforcement learning", "multi-agent systems", "game theory", "optimization", "decision making"],
    bio: "Reinforcement learning in multi-agent environments. Research on cooperative and competitive learning algorithms.",
    matchableText: "reinforcement learning multi-agent systems game theory optimization decision making cooperative learning competitive learning algorithms",
    publications: 19,
    profileURL: "/profile/david-kumar",
    email: "dkumar@gatech.edu",
    verified: true,
    github: "https://github.com/davidkumar-ml",
    linkedin: "https://linkedin.com/in/davidkumarml",
    department: "Machine Learning"
  },
  {
    name: "Dr. Rachel Green",
    university: "Princeton University",
    field: "Environmental Science",
    keywords: ["climate modeling", "environmental data", "sustainability", "climate change", "data analytics", "environmental monitoring"],
    bio: "Climate modeling and environmental data analysis. Developing predictive models for climate change impact assessment.",
    matchableText: "climate modeling environmental data sustainability climate change data analytics environmental monitoring predictive models impact assessment",
    publications: 14,
    profileURL: "/profile/rachel-green",
    email: "rgreen@princeton.edu",
    verified: true,
    github: "https://github.com/rachelgreen-env",
    linkedin: "https://linkedin.com/in/rachelgreenenv",
    department: "Environmental Science"
  },
  {
    name: "Dr. Ahmed Hassan",
    university: "University of Toronto",
    field: "Software Engineering",
    keywords: ["software engineering", "code analysis", "developer tools", "programming languages", "software quality"],
    bio: "Software engineering research focusing on automated code analysis and developer productivity tools.",
    matchableText: "software engineering code analysis developer tools programming languages software quality automated analysis developer productivity",
    publications: 25,
    profileURL: "/profile/ahmed-hassan",
    email: "ahassan@utoronto.ca",
    verified: true,
    github: "https://github.com/ahmedhassan-se",
    linkedin: "https://linkedin.com/in/ahmedhassanse",
    department: "Software Engineering"
  },
  {
    name: "Dr. Jennifer Liu",
    university: "Yale University",
    field: "Educational Technology",
    keywords: ["educational technology", "learning analytics", "student performance", "adaptive learning", "personalized education"],
    bio: "Educational technology and learning analytics. Research on personalized learning systems and student performance prediction.",
    matchableText: "educational technology learning analytics student performance adaptive learning personalized education predictive models learning systems",
    publications: 17,
    profileURL: "/profile/jennifer-liu",
    email: "jliu@yale.edu",
    verified: true,
    github: "https://github.com/jenniferliu-edtech",
    linkedin: "https://linkedin.com/in/jenniferliuedtech",
    department: "Educational Technology"
  },
  {
    name: "Dr. Robert Kim",
    university: "University of Chicago",
    field: "Economics",
    keywords: ["behavioral economics", "game theory", "experimental economics", "decision theory", "market analysis"],
    bio: "Behavioral economics and experimental game theory. Studying decision-making processes in economic contexts.",
    matchableText: "behavioral economics game theory experimental economics decision theory market analysis decision making economic contexts experimental design",
    publications: 21,
    profileURL: "/profile/robert-kim",
    email: "rkim@uchicago.edu",
    verified: true,
    linkedin: "https://linkedin.com/in/robertkimecon",
    department: "Economics"
  },
  {
    name: "Dr. Maria Silva",
    university: "NYU",
    field: "Digital Media",
    keywords: ["digital media", "social networks", "content analysis", "media studies", "digital humanities"],
    bio: "Digital media research with focus on social network analysis and content propagation in online communities.",
    matchableText: "digital media social networks content analysis media studies digital humanities social network analysis content propagation online communities",
    publications: 13,
    profileURL: "/profile/maria-silva",
    email: "msilva@nyu.edu",
    verified: true,
    github: "https://github.com/mariasilva-media",
    linkedin: "https://linkedin.com/in/mariasilvadigital",
    department: "Digital Media"
  },
  {
    name: "Dr. Thomas Anderson",
    university: "University of Michigan",
    field: "Cybersecurity",
    keywords: ["cybersecurity", "network security", "threat detection", "intrusion detection", "security analytics"],
    bio: "Cybersecurity research focusing on advanced threat detection and network security analytics using machine learning.",
    matchableText: "cybersecurity network security threat detection intrusion detection security analytics machine learning advanced threats network analytics",
    publications: 26,
    profileURL: "/profile/thomas-anderson",
    email: "tanderson@umich.edu",
    verified: true,
    github: "https://github.com/thomasanderson-sec",
    linkedin: "https://linkedin.com/in/thomasandersonsec",
    department: "Cybersecurity"
  }
];

// Helper function to initialize the researcher database
export const initializeResearcherDatabase = () => {
  return initialResearchers;
}; 